name: hafiz_test
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+9

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.15
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  cupertino_icons: ^1.0.5
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  marquee: ^2.3.0
  audio_video_progress_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - shorebird.yaml

  fonts:
    - family: Kitab
      fonts:
        - asset: assets/fonts/Kitab-Bold.ttf
    - family: Quran
      fonts:
        - asset: assets/fonts/me_quran.ttf
