name: hafiz_test
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  shared_preferences: ^2.1.2
  audioplayers: ^5.1.0
  shimmer: ^3.0.0
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_automation: ^2.0.0
  cupertino_icons: ^1.0.5
  flutter_animate: ^4.2.0+1
  intl: ^0.18.0
  flutter_islamic_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Quran
      fonts:
        - asset: assets/fonts/me_quran.ttf
